name: Deploy Vue App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkoout
      uses: actions/checkout@v3

    - name: Use Node v18.7.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.7.0
        cache: 'npm'
    - run: npm install
    - run: npm run build

    - name: Setup 404 Routing
      run: cd dist && cp index.html 404.html
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist
